# Generated by Django 5.1.2 on 2024-11-28 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_ong_imagem'),
        ('usuarios', '0010_alter_ong_whatsapp'),
    ]

    operations = [
    ]
