# Generated by Django 5.1.2 on 2024-11-28 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_merge_0004_alter_ong_imagem_0010_alter_ong_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ong',
            name='imagem',
            field=models.CharField(blank=True, default='https://www.google.com/imgres?q=default%20coloque%20sua%20imagem&imgurl=https%3A%2F%2Fwww.quadrorama.com.br%2Fwp-content%2Fuploads%2F2018%2F05%2Fquadro-com-foto-imagem-personalizada.png&imgrefurl=https%3A%2F%2Fwww.quadrorama.com.br%2Fproduto%2Ffoto-personalizada%2F&docid=Rf3tWzXG5ZJ58M&tbnid=JyJzwRzOMJN5vM&vet=12ahUKEwiPsNa60_qJAxVYq5UCHfzfCAYQM3oECFAQAA..i&w=351&h=497&hcb=2&ved=2ahUKEwiPsNa60_qJAxVYq5UCHfzfCAYQM3oECFAQAA', max_length=1000, null=True),
        ),
    ]
