# Generated by Django 5.1.2 on 2024-11-14 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ONG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'permissions': [('can_manage_local', 'Can manage local'), ('can_manage_residuos', 'Can manage residuos')],
            },
        ),
    ]
